# =========================
# POSTGRES
# =========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: mooddb
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

# =========================
# MOOD-TRACKER
# =========================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mood-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mood
  template:
    metadata:
      labels:
        app: mood
    spec:
      containers:
        - name: mood-tracker
          image: mood-tracker-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            # ---- SPRING DATASOURCE (ÇOK KRİTİK) ----
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/mooddb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres

            # ---- JPA ----
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_JPA_SHOW_SQL
              value: "true"

            # ---- Kubernetes Downward API ----
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: mood-service
spec:
  type: ClusterIP
  selector:
    app: mood
  ports:
    - port: 8080
      targetPort: 8080
