apiVersion: v1
kind: Service
metadata:
  name: kong
spec:
  type: NodePort
  selector:
    app: kong
  ports:
    - name: proxy
      port: 6060
      targetPort: 6060
      nodePort: 30060

    - name: admin
      port: 6061
      targetPort: 6061
      nodePort: 30061
